### ISSUE TITLE
bug/AttributeError-RetryConfig

### ISSUE THREAD

**Issue by Avi777** [Unstructured-IO/unstructured-python-client#101]
**Error traceback:**
```shell
File "/usr/local/lib/python3.11/site-packages/unstructured_client/utils/retries.py", line 106, in retry_with_backoff
    return func()
           └ <function retry.<locals>.do_request at 0x7317646d47c0>
  File "/usr/local/lib/python3.11/site-packages/unstructured_client/utils/retries.py", line 79, in do_request
    if retries.config.config.retry_connection_errors:
       │       └ <unstructured_client.utils.retries.RetryConfig object at 0x7317646e0cd0>
       └ <unstructured_client.utils.retries.Retries object at 0x7317646e0ad0>

AttributeError: 'RetryConfig' object has no attribute 'config'
```

An `AttributeError` is raised when attempting to ingest a large PDF document using  unstructured-client.

**To Reproduce**
I'm using `unstructured-client==0.22.0` and `tiangolo/uvicorn-gunicorn-fastapi:python3.11-slim` docker image with an attempt to ingest a PDF document with more than 200 pages.

I think the error is because of timeout and it tries to retry the parsing.

**Comment by awalker4** [comment]
Hi there, you're probably right that it's retrying on a timeout. A few things:
* For a 200 page doc I'd highly recommend our new split page mode which will send portions of the pdf concurrently for a massive speedup. [Here's](https://github.com/Unstructured-IO/unstructured-python-client/tree/v0.22.0?tab=readme-ov-file#splitting-pdf-by-pages) the documentation on it for v0.22.0. We're just about to release a new version of the client which has some improved page splitting logic.
* As for the RetryConfig error, I believe it's also resolved in the newest version - I'll let you know when this is published.

**Comment by Avi777** [comment]
Thanks. Setting `include_page-breaks` parameter to `True` seems to alleviate the issue.
