### ISSUE TITLE
bug/nest-asyncio conflict with uvloop

### ISSUE THREAD

**Issue by haoshan98** [Unstructured-IO/unstructured-python-client#133]
**Describe the bug**
The `nest-asyncio` used by `split_pdf_hook.py` triggered the error. The conflict occurs when trying to use `nest-asyncio` together with `uvloop` custom event loop.

> E       RuntimeError: Endpoint http://localhost:6969/api/v1/gen_tables/knowledge/upload_file returned 500 error: {"object":"error","error":"unexpected_error","message":"Opss sorry we ran into an unexpected error. Please try again later.","detail":"Can't patch loop of type <class 'uvloop.Loop'>","request_id":"01906e81-ff60-7966-9f7b-cf3798aecb94","exception":"ValueError"}

**Comment by awalker4** [comment]
Hi @haoshan98, the linked PR will fix this error. Unfortunately, the current splitting implementation will not work with uvloop, so here we can fallback to not splitting pdfs. Keep an eye on #135 for a full overhaul of our asyncio code.

**Comment by awalker4** [comment]
This error is fixed in 0.25.2
