### ISSUE TITLE
How to establish localhost service

### ISSUE THREAD

**Issue by yuanjie-ai** [Unstructured-IO/unstructured-python-client#27]
How to establish localhost service

**Comment by hubert-rutkowski85** [comment]
Hi yuanjie, I assume you want to connect to unstructured-api that is setup on localhost.

That is explained on main repo page: https://github.com/Unstructured-IO/unstructured-python-client#change-the-base-url

Here is more documentation for using the library: https://unstructured-io.github.io/unstructured/apis/api_sdks.html

If you have specific usage questions, please ask on community slack: https://short.unstructured.io/pzw05l7

Closing.
