### ISSUE TITLE
bug/chore: Add all unstructured partition parameters to openapi.json and update sdk

### ISSUE THREAD

**Issue by Coniferish** [Unstructured-IO/unstructured-python-client#52]
Some partition parameters are not present in the SDK. The goal of this issue is to identify and update the SDK with those parameters. For example, `content_type` and `find_subtable` are chunking parameters present in the openapi.json in unstructured-api, but they are not in the PartitionParameters here. The process for adding these to the SDK should also be documented as this issue is resolved.

**Comment by awalker4** [comment]
Will close this one and we can introduce api params from the library as needed.
