### ISSUE TITLE
chore/custom client logic is moved to hooks

### ISSUE THREAD

**Issue by awalker4** [Unstructured-IO/unstructured-python-client#60]
**Definition of done**
* The custom logic for pdf splitting, retry logging, and server_url fixing are moved to the appropriate lifecycle hook
* All of this logic is tested locally and still works
* Client is regenerated without needing to restore any human written code

**Comment by awalker4** [comment]
Note that the server_url stuff will have to be a before_request hook. Sounds like we can't raise an error during the sdk_init hook.

**Comment by Coniferish** [comment]
@awalker4, just seeing your comment about the `server_url` hook again. I did implement it as a sdk_init hook. We didn't raise any errors before with the decorator, so it works fine as it is. Are you thinking we should be raising errors, though? The hook just removes any path that's passed in (e.g. /general/v0/general) and fixes the url scheme (http/https).

**Comment by awalker4** [comment]
Ah, we should be good if we weren't already throwing anything!
