### ISSUE TITLE
Cannot get the content out of embedded object in PPT files

### ISSUE THREAD

**Issue by kumar-pondicherry** [Unstructured-IO/unstructured-python-client#70]
The code is extracting the content out of power point slides . But it is not getting the content out of embedded objects in the power point slides

**Comment by scanny** [comment]
@kumar-pondicherry describe a particular example more specifically, like a slide has {a, b, c} shapes and this one that is a {x} is not producing an element.

If you mean the slide contains an embedded Excel spreadsheet or something, those are not extracted.

**Comment by kumar-pondicherry** [comment]
Hi Steve - Let us say slide 1 has a text along with a image with some text
.We are not able to extract the text from the embedded image .

Kumar

**Comment by scanny** [comment]
Ah, okay. This should work when using the API (incuding freemium). Make sure to use `strategy="hi_res"` when doing the partitioning call.

Closing as resolved, but feel free to reopen if you need more help getting this working :)
