### ISSUE TITLE
feat: support `content_type` parameter

### ISSUE THREAD

**Issue by Coniferish** [Unstructured-IO/unstructured-python-client#95]
**Is your feature request related to a problem? Please describe.**
`content_type` is not a supported parameter of the SDK though it was supported by `partition_via_api` before we switched to the SDK: https://github.com/Unstructured-IO/unstructured/issues/2584.

**Describe the solution you'd like**
We have an open request for speakeasy to support this, but as a quick fix, we can modify the overlay.yaml to add `content_type` as a parameter and add a custom hook.

**Comment by Coniferish** [comment]
Related discussion: https://github.com/Unstructured-IO/core-product/issues/371

**Comment by awalker4** [comment]
Closing this as I'm adding `content_type` as an API param. The SDKs will autogenerate with this soon. Actually, the Python v2 SDK also lets us set the content_type, so we'll have multiple options soon.
